{"name": "Проверка ошибки при получении заказа без номера", "status": "passed", "steps": [{"name": "Попытка получить заказ без указания track номера", "status": "passed", "start": 1760866198273, "stop": 1760866198725}], "start": 1760866198273, "stop": 1760866198726, "uuid": "072b8f18-f318-4264-85cf-d9f968d52d1a", "historyId": "e4f5f0f6d841da2c29921b6a81ef48c4", "testCaseId": "e4f5f0f6d841da2c29921b6a81ef48c4", "fullName": "tests.tests_orders.test_order_get_by_track.TestOrderGetByTrack#test_order_get_by_track_error_without_track", "labels": [{"name": "parentSuite", "value": "tests.tests_orders"}, {"name": "suite", "value": "test_order_get_by_track"}, {"name": "subSuite", "value": "TestOrderGetByTrack"}, {"name": "host", "value": "Sergei"}, {"name": "thread", "value": "9908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_orders.test_order_get_by_track"}], "titlePath": ["tests", "tests_orders", "test_order_get_by_track.py", "TestOrderGetByTrack"]}